/* =============================================================================
   BUKALEMUN — scripts/lib/tokens.mjs
   Shared colour maths and token-graph resolution, used by the contrast audit
   and by the derivation tool. Models enough of the CSS cascade to answer
   "what colour does this token actually compute to, for this skin, in this
   colour mode" without a browser.
   ========================================================================== */

import { readFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';

export const GENERATED_MARK = '/* ==== derived contrast tokens — generated by scripts/derive-contrast.mjs';
export const GENERATED_END = '/* ==== end derived contrast tokens ==== */';

/* The accent variants: two hue-shifted copies of each skin's accent family,
   generated by scripts/derive-variants.mjs and switched with data-bk-accent. */
export const VARIANTS = ['warm', 'cool'];
export const VARIANT_MARK = '/* ==== accent variants — generated by scripts/derive-variants.mjs';
export const VARIANT_END = '/* ==== end accent variants ==== */';

/* ------------------------------------------------------------- colour ---- */

export function parseColor(value) {
  if (value == null) return null;
  const v = String(value).trim();

  const hex = v.match(/^#([0-9a-f]{3,8})$/i);
  if (hex) {
    const h = hex[1];
    const ex = (s) => parseInt(s.length === 1 ? s + s : s, 16);
    if (h.length === 3 || h.length === 4) {
      return { r: ex(h[0]), g: ex(h[1]), b: ex(h[2]), a: h.length === 4 ? ex(h[3]) / 255 : 1 };
    }
    if (h.length === 6 || h.length === 8) {
      return {
        r: parseInt(h.slice(0, 2), 16),
        g: parseInt(h.slice(2, 4), 16),
        b: parseInt(h.slice(4, 6), 16),
        a: h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1
      };
    }
  }

  const fn = v.match(/^rgba?\(([^)]+)\)$/i);
  if (fn) {
    const parts = fn[1].split(/[\s,/]+/).filter(Boolean);
    const num = (s) => (s.endsWith('%') ? (parseFloat(s) / 100) * 255 : parseFloat(s));
    const raw = parts[3];
    const a = raw === undefined ? 1 : (raw.endsWith('%') ? parseFloat(raw) / 100 : parseFloat(raw));
    const c = { r: num(parts[0]), g: num(parts[1]), b: num(parts[2]), a };
    return Number.isFinite(c.r) && Number.isFinite(c.g) && Number.isFinite(c.b) ? c : null;
  }

  if (v === 'transparent') return { r: 0, g: 0, b: 0, a: 0 };
  if (v === 'white') return { r: 255, g: 255, b: 255, a: 1 };
  if (v === 'black') return { r: 0, g: 0, b: 0, a: 1 };
  return null;
}

export const composite = (fg, bg) => ({
  r: fg.r * fg.a + bg.r * (1 - fg.a),
  g: fg.g * fg.a + bg.g * (1 - fg.a),
  b: fg.b * fg.a + bg.b * (1 - fg.a),
  a: 1
});

export function luminance(c) {
  const f = (v) => {
    const n = v / 255;
    return n <= 0.03928 ? n / 12.92 : Math.pow((n + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * f(c.r) + 0.7152 * f(c.g) + 0.0722 * f(c.b);
}

export function contrast(fg, bg) {
  const l1 = luminance(fg);
  const l2 = luminance(bg);
  return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
}

export function toHex(c) {
  const clamp = (v) => Math.max(0, Math.min(255, Math.round(v)));
  const h = (v) => clamp(v).toString(16).padStart(2, '0');
  return '#' + h(c.r) + h(c.g) + h(c.b);
}

export function rgbToHsl({ r, g, b }) {
  const rn = r / 255, gn = g / 255, bn = b / 255;
  const max = Math.max(rn, gn, bn), min = Math.min(rn, gn, bn);
  const l = (max + min) / 2;
  let h = 0, s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === rn) h = ((gn - bn) / d + (gn < bn ? 6 : 0));
    else if (max === gn) h = (bn - rn) / d + 2;
    else h = (rn - gn) / d + 4;
    h /= 6;
  }
  return { h, s, l };
}

export function hslToRgb({ h, s, l }) {
  if (s === 0) { const v = l * 255; return { r: v, g: v, b: v, a: 1 }; }
  const hue = (p, q, t) => {
    let tt = t;
    if (tt < 0) tt += 1;
    if (tt > 1) tt -= 1;
    if (tt < 1 / 6) return p + (q - p) * 6 * tt;
    if (tt < 1 / 2) return q;
    if (tt < 2 / 3) return p + (q - p) * (2 / 3 - tt) * 6;
    return p;
  };
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  return {
    r: hue(p, q, h + 1 / 3) * 255,
    g: hue(p, q, h) * 255,
    b: hue(p, q, h - 1 / 3) * 255,
    a: 1
  };
}

/**
 * Find the nearest variant of `color` (hue and saturation preserved) that hits
 * `target` contrast against every background in `backgrounds`. Walks lightness
 * in the direction that helps, and returns null if even the extreme fails.
 */
export function fitLightness(color, backgrounds, target) {
  const bgs = backgrounds.filter(Boolean);
  if (!bgs.length) return null;
  const worst = (c) => Math.min(...bgs.map((bg) => contrast(c, bg)));
  if (worst(color) >= target) return color;

  const base = rgbToHsl(color);
  const avgBgLum = bgs.reduce((sum, bg) => sum + luminance(bg), 0) / bgs.length;
  const directions = avgBgLum > 0.4 ? [-1, 1] : [1, -1];

  // Try to keep the accent's chroma. Only when a fully saturated variant cannot
  // reach the target at any lightness do we start bleeding saturation out — and
  // then only as far as needed, so the colour still reads as the skin's.
  const saturations = [1, 0.82, 0.64, 0.46, 0.28, 0.12, 0];

  for (const satScale of saturations) {
    const s = base.s * satScale;
    let best = null;
    for (const dir of directions) {
      for (let step = 1; step <= 100; step++) {
        const l = base.l + dir * step * 0.01;
        if (l < 0 || l > 1) break;
        const candidate = Object.assign(hslToRgb({ h: base.h, s, l }), { a: 1 });
        if (worst(candidate) >= target) {
          if (!best || step < best.step) best = { color: candidate, step };
          break;
        }
      }
      if (best) break;
    }
    if (best) return best.color;
  }

  // Nothing in this hue works against every background at once (a light chip on
  // a dark page, say). Fall back to plain black or white, whichever is better.
  const ends = [{ r: 0, g: 0, b: 0, a: 1 }, { r: 255, g: 255, b: 255, a: 1 }];
  const ranked = ends.sort((a, b) => worst(b) - worst(a));
  return worst(ranked[0]) >= target ? ranked[0] : null;
}

/* --------------------------------------------------------------- parse --- */

export const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, '');

function stripBetween(css, mark, endMark) {
  const start = css.indexOf(mark);
  if (start === -1) return css;
  const end = css.indexOf(endMark, start);
  if (end === -1) return css.slice(0, start);
  return css.slice(0, start) + css.slice(end + endMark.length);
}

export const stripGenerated = (css) => stripBetween(css, GENERATED_MARK, GENERATED_END);
export const stripVariants = (css) => stripBetween(css, VARIANT_MARK, VARIANT_END);

/**
 * Collect custom-property declarations from every block whose selector matches.
 * File-local privates (`--_gold`, `--_face`) count: the browser resolves them
 * like any other variable, so a resolver that ignored them would fail to see
 * through `var(--bk-primary: var(--_orange))` and silently mis-audit the skin.
 */
export function declarationsFor(css, selectorTest) {
  const out = {};
  const body = stripComments(css);
  for (const block of body.split('}')) {
    const idx = block.lastIndexOf('{');
    if (idx === -1) continue;
    const selector = block.slice(0, idx).split('{').pop().trim();
    if (!selectorTest(selector)) continue;
    for (const m of block.slice(idx + 1).matchAll(/(--(?:bk|_)[\w-]+)\s*:\s*([^;]+);/g)) {
      out[m[1]] = m[2].trim();
    }
  }
  return out;
}

/**
 * @param {string} srcDir
 * @param {{ includeGenerated?: boolean }} [opts]
 *   The audit wants the *effective* palette, generated block included. The
 *   derivation tool wants the hand-authored palette only, so it can recompute
 *   from scratch instead of layering fixes on top of fixes.
 */
export function loadTokens(srcDir, opts = {}) {
  const includeGenerated = opts.includeGenerated !== false;
  const includeVariants = opts.includeVariants !== false;
  const tokensCss = readFileSync(join(srcDir, 'core', 'tokens.css'), 'utf8');
  const BASE = declarationsFor(tokensCss, (s) => s.includes(':where(:root)'));
  const BASE_DARK = declarationsFor(
    tokensCss,
    (s) => s.includes('[data-bk-theme="dark"]') && !s.includes('auto')
  );

  const files = readdirSync(join(srcDir, 'styles')).filter((f) => f.endsWith('.css')).sort();
  const SKINS = { default: { base: {}, dark: {}, light: {}, file: null } };
  for (const file of files) {
    const name = basename(file, '.css');
    const raw = readFileSync(join(srcDir, 'styles', file), 'utf8');
    let css = includeGenerated ? raw : stripGenerated(raw);
    if (!includeVariants) css = stripVariants(css);
    const skin = `[data-bk-style="${name}"]`;
    const blocks = (prefix) => ({
      base: declarationsFor(css, (s) => s === prefix),
      dark: declarationsFor(css, (s) => s === `${prefix}[data-bk-theme="dark"]`),
      light: declarationsFor(css, (s) => s === `${prefix}[data-bk-theme="light"]`)
    });
    const variants = {};
    for (const v of VARIANTS) {
      const b = blocks(`${skin}[data-bk-accent="${v}"]`);
      if (Object.keys(b.base).length || Object.keys(b.dark).length || Object.keys(b.light).length) variants[v] = b;
    }
    SKINS[name] = { file: join(srcDir, 'styles', file), ...blocks(skin), variants };
  }
  return { BASE, BASE_DARK, SKINS };
}

/**
 * The effective token map for one skin in one colour mode, following the same
 * order the browser resolves: core tokens, core dark palette (zero specificity,
 * so a skin always wins), the skin's base block, then its mode block.
 */
export function tokenMap({ BASE, BASE_DARK, SKINS }, skin, mode, variant = null) {
  const s = SKINS[skin];
  const map = Object.assign({}, BASE);
  if (mode === 'dark') Object.assign(map, BASE_DARK);
  Object.assign(map, s.base);
  Object.assign(map, mode === 'dark' ? s.dark : s.light);
  // A variant block has one more attribute than the block it shadows, so it
  // wins at every layer: its base over the skin's base, its mode over the
  // skin's mode. Layer it the same way.
  const v = variant && s.variants && s.variants[variant];
  if (v) {
    Object.assign(map, v.base);
    Object.assign(map, mode === 'dark' ? v.dark : v.light);
  }
  return map;
}

/** Every (skin, mode, variant) the audit and the lock should cover. */
export function combinations(tokens) {
  const out = [];
  for (const skin of Object.keys(tokens.SKINS)) {
    const variants = [null, ...Object.keys(tokens.SKINS[skin].variants || {})];
    for (const mode of ['light', 'dark']) for (const variant of variants) out.push({ skin, mode, variant });
  }
  return out;
}

export function resolve(map, value, depth = 0) {
  if (value == null || depth > 12) return null;
  const v = String(value).trim();
  const direct = parseColor(v);
  if (direct) return direct;
  const m = v.match(/^var\(\s*(--[\w-]+)\s*(?:,\s*([\s\S]+))?\)$/);
  if (m) {
    if (map[m[1]] !== undefined) {
      const r = resolve(map, map[m[1]], depth + 1);
      if (r) return r;
    }
    if (m[2]) return resolve(map, m[2], depth + 1);
  }
  const mix = v.match(/^color-mix\(\s*in\s+([\w-]+)\s*,([\s\S]+)\)$/);
  if (mix) return resolveMix(map, mix[2], depth + 1);
  return null;
}

/**
 * `color-mix(in srgb, A p%, B q%)`. The core hover/active tokens are built with
 * it, so the audit has to see through it. Mixing is done in sRGB whatever the
 * declared space: the tokens that matter to contrast say `in srgb` on purpose,
 * and for the small ratios used elsewhere the difference is below what the
 * 1% lightness steps of the deriver can express anyway.
 */
function resolveMix(map, args, depth) {
  const parts = splitTopLevel(args);
  if (parts.length !== 2) return null;
  const side = (s) => {
    const pm = s.match(/^([\s\S]*?)\s*(\d+(?:\.\d+)?)%$/) || s.match(/^(\d+(?:\.\d+)?)%\s+([\s\S]*)$/);
    let color = s, pct = null;
    if (pm) {
      if (/^\d/.test(pm[1])) { pct = parseFloat(pm[1]); color = pm[2]; }
      else { color = pm[1]; pct = parseFloat(pm[2]); }
    }
    return { color: resolve(map, color.trim(), depth), pct };
  };
  const a = side(parts[0].trim()), b = side(parts[1].trim());
  if (!a.color || !b.color) return null;
  let pa = a.pct, pb = b.pct;
  if (pa == null && pb == null) { pa = 50; pb = 50; }
  else if (pa == null) pa = 100 - pb;
  else if (pb == null) pb = 100 - pa;
  const sum = pa + pb;
  if (!sum) return null;
  const wa = pa / sum, wb = pb / sum;
  // Premultiplied alpha, the way the spec interpolates.
  const alpha = a.color.a * wa + b.color.a * wb;
  const ch = (k) => alpha ? (a.color[k] * a.color.a * wa + b.color[k] * b.color.a * wb) / alpha : 0;
  return { r: ch('r'), g: ch('g'), b: ch('b'), a: alpha * (sum / 100) };
}

function splitTopLevel(s) {
  const out = [];
  let depth = 0, cur = '';
  for (const c of s) {
    if (c === '(') depth++;
    if (c === ')') depth--;
    if (c === ',' && depth === 0) { out.push(cur); cur = ''; continue; }
    cur += c;
  }
  out.push(cur);
  return out;
}

export const get = (map, token) => resolve(map, map[token]);

/* ---------------------------------------------------------------- rules -- */

export const AA = 4.5;
export const AA_LARGE = 3.0;
export const ROLES = ['primary', 'secondary', 'success', 'warning', 'danger', 'info', 'neutral'];

/** Every foreground/background pair the components actually paint. */
export function pairsFor(map) {
  const pairs = [];
  const bg = get(map, '--bk-bg');
  const layers = {
    bg,
    surface: get(map, '--bk-surface'),
    'surface-2': get(map, '--bk-surface-2'),
    'surface-3': get(map, '--bk-surface-3')
  };

  const flat = (c) => (c && bg ? composite(c, bg) : c);
  const add = (label, fgToken, bgColor, min) => {
    const raw = get(map, fgToken);
    if (!raw || !bgColor) return;
    pairs.push({ label, token: fgToken, ratio: contrast(composite(raw, bgColor), bgColor), min, bg: bgColor });
  };

  for (const [name, layer] of Object.entries(layers)) {
    if (!layer) continue;
    const base = flat(layer);
    add(`text on ${name}`, '--bk-text', base, AA);
    add(`text-muted on ${name}`, '--bk-text-muted', base, AA);
    add(`text-subtle on ${name}`, '--bk-text-subtle', base, AA_LARGE);
  }

  for (const role of ROLES) {
    const fill = get(map, `--bk-${role}`);
    if (fill) add(`on-${role} over ${role}`, `--bk-on-${role}`, flat(fill), AA);
    // A solid button keeps its label while its fill changes under the pointer,
    // so the label has to read on the hover and active fills too.
    const hover = get(map, `--bk-${role}-hover`);
    if (hover) add(`on-${role} over ${role}-hover`, `--bk-on-${role}`, flat(hover), AA);
    const active = get(map, `--bk-${role}-active`);
    if (active) add(`on-${role} over ${role}-active`, `--bk-on-${role}`, flat(active), AA);
    const soft = get(map, `--bk-${role}-soft`);
    if (soft) add(`${role}-on-soft over ${role}-soft`, `--bk-${role}-on-soft`, flat(soft), AA);
    if (layers.bg) add(`${role}-text on bg`, `--bk-${role}-text`, layers.bg, AA);
    if (layers.surface) add(`${role}-text on surface`, `--bk-${role}-text`, flat(layers.surface), AA);
    if (layers['surface-2']) add(`${role}-text on surface-2`, `--bk-${role}-text`, flat(layers['surface-2']), AA);
  }

  // Cards and overlays may paint their own surface rather than --bk-surface;
  // body copy is set on both. A card background that is only right in one
  // colour mode is exactly the kind of leak this catches.
  for (const [name, token] of [['card', '--bk-card-bg'], ['overlay', '--bk-overlay-surface']]) {
    const c = get(map, token);
    if (!c) continue;
    add(`text on ${name}`, '--bk-text', flat(c), AA);
    add(`text-muted on ${name}`, '--bk-text-muted', flat(c), AA);
    add(`primary-text on ${name}`, '--bk-primary-text', flat(c), AA);
  }

  const inverted = get(map, '--bk-surface-inverted');
  if (inverted) add('text-inverted on surface-inverted', '--bk-text-inverted', flat(inverted), AA);

  const fieldBg = get(map, '--bk-field-bg');
  if (fieldBg) {
    add('text in field', '--bk-text', flat(fieldBg), AA);
    add('placeholder in field', '--bk-field-placeholder', flat(fieldBg), AA_LARGE);
  }

  const tipBg = get(map, '--bk-tooltip-bg');
  if (tipBg) add('tooltip text', '--bk-tooltip-fg', flat(tipBg), AA);

  return pairs;
}
